### ISSUE TITLE
Blank default value for property should be used only if prop type is String

### ISSUE THREAD

**Issue by ninoish** [developerforce/lwc-builder#94]
If default values for property left blank with prop type other than String, it causes errors like `The default value you specified '' is not a valid integer.`.

**Comment by rahulgawale** [comment]
I think I have fixed this in the UI repo. Here is the [PR](https://github.com/developerforce/lwc-builder-ui/pulls)

**Comment by ninoish** [comment]
Fixed in UI PR [#116](https://github.com/developerforce/lwc-builder-ui/pull/116)
